spring.application.name=Econaunts
spring.datasource.url=jdbc:postgresql://localhost:5432/econauts
spring.datasource.username=postgres
spring.datasource.password=Chandu6262

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.address=0.0.0.0
server.port=8080

jwt.secret=mysupersecuresecretkeymysupersecuresecretkey12345

# access token (15 min)
jwt.expiration=900000

# refresh token (7 days)
jwt.refresh.expiration=604800000

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

razorpay.key=rzp_test_xxxxxxxxxxxx
razorpay.secret=xxxxxxxxxxxxxxx

cloudinary.cloud_name=Root
cloudinary.api_key=574721993332342
cloudinary.api_secret=wlng1ztaux8--sTFOCg_vcFL6os